### PR TITLE
Do some cleanup and refactoring

### PR DESCRIPTION
**Pull request by Nashtare**

### CODE REVIEW

**Review by dvdplm — COMMENTED** [review]
lgtm, not much left here!

**Review by BGluth — APPROVED** [review]
Yeah look good! Also seems like you removed all of the now unused code. :+1:

**Comment by Nashtare** [comment]
Yeah, there's one more pass to do here once the decoder is cleaned up, as there is basically no need anymore for a wrapper around GenerationInputs (TxnIdx is not needed), but that can wait post merge

**Comment by BGluth** [comment]
Oh yeah. Perhaps we actually don't need the `txn_idx`. In the back of my mind I was thinking that the scheduler still needed it, but I guess it can just get the txn index from the index of the IR in the `Vec` it returns instead.

**Pull request merged**
